/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIClient;

import TCPClient.Message;
import com.google.gson.Gson;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DUNG BUI
 */
public class ScreenChatJInternalFrame extends javax.swing.JInternalFrame {
    Socket ss;
    String sendperson;
    String receiveperson;
    HashMap<String, ScreenChatJInternalFrame> chatwindows;
    HashMap<String, javax.swing.JTextArea> showChatOnScreenHashMap;
    javax.swing.JDesktopPane jDesktopPane1;
    OutputStream os = null;
    BufferedWriter bw = null;

    /**
     * Creates new form ScreenChatJInternalFrame
     * @param s
     * @param SendPerson
     * @param ReceivePerson
     * @param ChatWindows
     * @param showChatOnScreenHashMap
     * @param jDesktopPane1
     */
    public ScreenChatJInternalFrame(Socket s, String SendPerson, String ReceivePerson, HashMap<String,ScreenChatJInternalFrame> ChatWindows, HashMap<String, javax.swing.JTextArea> showChatOnScreenHashMap, javax.swing.JDesktopPane jDesktopPane1) {
        initComponents();
        this.ss = s;
        this.sendperson = SendPerson;
        this.receiveperson = ReceivePerson;
        this.chatwindows = ChatWindows;
        this.showChatOnScreenHashMap = showChatOnScreenHashMap;
        this.jDesktopPane1 = jDesktopPane1;
        load();
    }
    
    private void load(){
        this.jLabelUserNameMess.setText(this.receiveperson);
        showChatOnScreenHashMap.put(this.receiveperson, jTextAreaConversation);
        try {
            os = ss.getOutputStream();
            bw = new BufferedWriter(new OutputStreamWriter(os));
            
        } catch (IOException ex) {
            Logger.getLogger(ScreenChatJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreenMess = new javax.swing.JPanel();
        jLabelUserNameMess = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSendFile = new javax.swing.JButton();
        jTextFieldTypeMess = new javax.swing.JTextField();
        jButtonSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaConversation = new javax.swing.JTextArea();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanelScreenMess.setBackground(new java.awt.Color(0, 255, 255));

        jLabelUserNameMess.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabelUserNameMess.setText("Lan");

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        jButtonSendFile.setBackground(new java.awt.Color(102, 255, 102));
        jButtonSendFile.setText("Send file");

        jTextFieldTypeMess.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonSend.setBackground(new java.awt.Color(255, 204, 51));
        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTypeMess, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSend)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTypeMess, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSendFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTextAreaConversation.setEditable(false);
        jTextAreaConversation.setBackground(new java.awt.Color(51, 204, 255));
        jTextAreaConversation.setColumns(20);
        jTextAreaConversation.setRows(5);
        jScrollPane2.setViewportView(jTextAreaConversation);

        javax.swing.GroupLayout jPanelScreenMessLayout = new javax.swing.GroupLayout(jPanelScreenMess);
        jPanelScreenMess.setLayout(jPanelScreenMessLayout);
        jPanelScreenMessLayout.setHorizontalGroup(
            jPanelScreenMessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScreenMessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelScreenMessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelScreenMessLayout.createSequentialGroup()
                        .addComponent(jLabelUserNameMess, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelScreenMessLayout.setVerticalGroup(
            jPanelScreenMessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenMessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserNameMess, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelScreenMess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelScreenMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        if(!this.jTextFieldTypeMess.getText().equalsIgnoreCase("")){
            String messString = this.jTextFieldTypeMess.getText().trim();
            this.jTextAreaConversation.setText(this.jTextAreaConversation.getText().trim() + "\n" + messString);
            
            Message message = new Message(2, sendperson, receiveperson, messString);
            
            Gson gson = new Gson();
            
            String sendMessString = gson.toJson(message, Message.class);
        
            try {
                bw.write(sendMessString);
                bw.newLine();
                bw.flush();
            } catch (IOException ex) {
                Logger.getLogger(ScreenChatJInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jTextFieldTypeMess.setText("");
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
//        if(chatwindows.containsKey(receiveperson)){
//                    System.out.println("tim thay screen chat");
//                    chatwindows.get(receiveperson).setVisible(false);
//                }else
//                    System.out.println("khong tim thay screen chat");
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonSendFile;
    private javax.swing.JLabel jLabelUserNameMess;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelScreenMess;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaConversation;
    private javax.swing.JTextField jTextFieldTypeMess;
    // End of variables declaration//GEN-END:variables
}
